name: ansible-test
on: [push, pull_request]
jobs:
  test:
    uses: pleme-io/substrate/.github/workflows/ansible-collection-ansible-test.yml@main
    with:
      namespace: drzln0
      name: akeyless
