name: ci
on: [push, pull_request]
jobs:
  check:
    uses: pleme-io/substrate/.github/workflows/ansible-collection-ci.yml@main
    with:
      openapi-spec-url: https://raw.githubusercontent.com/akeylesslabs/akeyless-go/master/api/openapi.yaml
