name: release
on:
  push:
    tags: ['v*']
  workflow_dispatch: {}
jobs:
  release:
    uses: pleme-io/substrate/.github/workflows/ansible-collection-release.yml@main
    secrets:
      ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
